spring:
  application:
    name: tensai-cms-api

  profiles:
    active: dev

  flyway:
    enabled: true
    baseline-on-migrate: true # Safely initializes Flyway if the DB already has existing tables

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  modulith:
    events:
      completion-mode: update
      republish-outstanding-events-on-restart: true

springdoc:
  api-docs:
    path: /v3/api-docs # JSON documentation endpoint
    version: openapi_3_1 # Enforces the OpenAPI 3.1 standard
  swagger-ui:
    default-models-expand-depth: -1
    path: /swagger-ui.html # Web UI landing page