spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tensaicms
    username: cms_user
    password: cms_password

  jpa:
    hibernate:
      ddl-auto: none

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

security:
  allowed-origins: [ "*" ]
  telegram-header: "X-Internal-Secret"
  jwt-secret: ${JWT_SECRET}
  base-url: "http://localhost:8080"
  reset-password-path: "${security.base-url}/api/v1/auth/reset-password"

storage:
  s3:
    endpoint: http://localhost:9000 # Remove or leave empty for real AWS S3
    access-key: minioadmin
    secret-key: minioadmin
    region: us-east-1 # MinIO defaults to us-east-1
    bucket: cms-media-bucket